const LANG_KEY = 'xinco-lang';

const translations = {
  es: {
    // SPLASH
    'splash.x': 'X',
    'splash.i': 'I',
    'splash.n': 'N',
    'splash.c': 'C',
    'splash.o': 'O',
    // META
    'meta.desc': 'XINCO. Ropa con corte impecable y materiales premium. Envíos a todo el país.',
    'meta.ogdesc': 'Descubrí la colección de XINCO. Prendas con estilo único.',
    'meta.twdesc': 'Descubrí la colección de XINCO.',
    // CART
    'cart.title': 'TU CARRITO',
    'cart.subtotal': 'SUBTOTAL',
    'cart.shipping': 'ENVÍO',
    'cart.free': 'GRATIS',
    'cart.checkout': 'FINALIZAR COMPRA',
    'cart.continue': 'SEGUIR COMPRANDO',
    // MOBILE MENU
    'mobile.home': 'INICIO',
    'mobile.catalog': 'CATÁLOGO',
    'mobile.accessories': 'ACCESORIOS',
    'mobile.new': 'NOVEDADES',
    'mobile.exclusive': 'EXCLUSIVE',
    // SEARCH
    'search.title': 'BUSCAR',
    'search.hint': 'CTRL+K PARA ABRIR / ESC PARA CERRAR',
    'search.suggestions': 'SUGERENCIAS:',
    'search.shirts': 'REMERAS',
    'search.hoodies': 'BUZOS',
    'search.pants': 'PANTALONES',
    'search.new': 'NOVEDADES',
    'search.sale': 'SALE',
    'search.empty': 'SIN RESULTADOS — INTENTÁ CON OTRO TÉRMINO',
    // HEADER
    'header.login': 'ACCEDER',
    'header.customize': 'Personalizar',
    // NAV
    'nav.home': 'INICIO',
    'nav.catalog': 'CATÁLOGO',
    'nav.accessories': 'ACCESORIOS',
    'nav.new': 'NOVEDADES',
    'nav.exclusive': 'EXCLUSIVE',
    // THEME PANEL
    'theme.title': 'Tema',
    'theme.light': 'Claro',
    'theme.dark': 'Oscuro',
    'theme.soft': 'Suave',
    'theme.accent': 'Acento',
    // HERO
    'hero.explore': 'EXPLORAR COLECCIÓN',
    'hero.new': 'NOVEDADES',
    // CATEGORIES
    'categories.title': 'Categorías',
    'categories.shirts': 'Remeras',
    'categories.pants': 'Pantalones',
    'categories.hoodies': 'Buzos',
    'categories.accessories': 'Accesorios',
    // HOME SECTIONS
    'home.newarrivals.label': 'NEW ARRIVALS',
    'home.newarrivals.title': 'Acaban de caer',
    'home.newarrivals.seeall': 'VER TODO',
    'home.exclusive.label': 'EXCLUSIVE',
    'home.exclusive.title': 'Edición limitada',
    'home.exclusive.seeall': 'VER TODO',
    // PROMO
    'promo.apply': 'Aplicar código al pagar.',
    'promo.claim': 'CANJEAR AHORA',
    // TRUST BAR
    'trust.shipping.title': 'ENVÍO A TODO EL PAÍS',
    'trust.shipping.desc': 'Entregas en 3-7 días hábiles',
    'trust.returns.title': 'CAMBIOS SIN CARGO',
    'trust.returns.desc': 'Dentro de los 30 días',
    'trust.payment.title': 'PAGO SEGURO',
    'trust.payment.desc': 'Transferencia, débito o crédito',
    'trust.support.title': 'ATENCIÓN DIRECTA',
    'trust.support.desc': 'Respondemos al toque por WhatsApp',
    // ABOUT
    'about.label': 'LA MARCA',
    'about.text': 'Nacimos en Mar del Plata con una idea clara: romper con lo de siempre. XINCO no es solo ropa, es una forma de expresar quién sos. Prendas con corte impecable, materiales premium y un estilo que habla por sí solo. Cada colección está pensada para el que camina diferente.',
    'about.cta': 'CONOCÉ LA COLECCIÓN',
    // INSTAGRAM
    'instagram.label': '@XINCO.STORE',
    'instagram.title': 'Seguinos en Instagram',
    // FOOTER
    'footer.rights': 'Todos los derechos reservados.',
    'footer.location': 'Mar del Plata, Buenos Aires, Argentina.',
    'footer.shop': 'TIENDA',
    'footer.catalog': 'Catálogo',
    'footer.new': 'Novedades',
    'footer.hoodies': 'Buzos',
    'footer.shirts': 'Remeras',
    'footer.accessories': 'Accesorios',
    'footer.exclusive': 'EXCLUSIVE',
    'footer.help': 'AYUDA',
    'footer.sizeguide': 'Guía de Talles',
    'footer.shipping': 'Envíos',
    'footer.returns': 'Devoluciones',
    'footer.contact': 'Contacto',
    'footer.newsletter': 'NEWSLETTER',
    'footer.newsletter.desc': 'Enterate primero de los drops.',
    'footer.newsletter.email': 'tu@email.com',
    'footer.newsletter.ok': 'OK',
    'footer.copyright': '© 2025 XINCO — MAR DEL PLATA, BUENOS AIRES, ARGENTINA',
    // CATALOG PAGE
    'catalog.title': 'TODOS LOS ITEMS',
    'catalog.subtitle': 'Explorá nuestra colección.',
    'catalog.filter.category': 'CATEGORÍA',
    'catalog.filter.all': 'Todos',
    'catalog.filter.tshirts': 'Remeras',
    'catalog.filter.pants': 'Pantalones',
    'catalog.filter.hoodies': 'Buzos',
    'catalog.filter.jackets': 'Camperas',
    'catalog.filter.accessories': 'Accesorios',
    'catalog.filter.size': 'TALLE',
    'catalog.filter.color': 'COLOR',
    'catalog.filter.price': 'PRECIO',
    'catalog.filter.clear': 'LIMPIAR FILTROS',
    'catalog.sort': 'ORDENAR:',
    'catalog.sort.relevance': 'RELEVANCIA',
    'catalog.sort.price_asc': 'PRECIO: MENOR A MAYOR',
    'catalog.sort.price_desc': 'PRECIO: MAYOR A MENOR',
    'catalog.sort.newest': 'MÁS NUEVOS',
    'catalog.empty': 'NO SE ENCONTRARON PRODUCTOS',
    'catalog.empty.cta': 'VER TODOS',
    // ACCESSORIES PAGE
    'accessories.title': 'ACCESORIOS',
    'accessories.subtitle': 'Gorras, pulseras, aros, cadenas y más.',
    'accessories.sort': 'ORDENAR:',
    'accessories.sort.relevance': 'RELEVANCIA',
    'accessories.sort.price_asc': 'PRECIO: MENOR A MAYOR',
    'accessories.sort.price_desc': 'PRECIO: MAYOR A MENOR',
    'accessories.sort.newest': 'MÁS NUEVOS',
    'accessories.empty': 'NO HAY ACCESORIOS DISPONIBLES',
    // PRODUCT OVERLAY
    'product.breadcrumb.home': 'INICIO',
    'product.breadcrumb.catalog': 'CATÁLOGO',
    'product.breadcrumb.product': 'PRODUCTO',
    'product.zoom': 'ZOOM',
    'product.color': 'COLOR:',
    'product.size': 'TALLE:',
    'product.sizeguide': 'GUÍA DE TALLES',
    'product.addtocart': 'AGREGAR AL CARRITO',
    'product.favorite': 'GUARDAR EN FAVORITOS',
    'product.sku': 'SKU',
    'product.category': 'CATEGORÍA',
    'product.stock': 'STOCK',
    'product.shipping_info': 'ENVÍO GRATIS A PARTIR DE $95.000',
    'product.returns_info': '30 DÍAS DE GARANTÍA DE DEVOLUCIÓN',
    'product.related': 'TAMBIÉN TE PUEDE GUSTAR',
    'product.reviews': 'RESEÑAS',
    'product.reviews.count': '0 OPINIONES',
    'product.reviews.write': 'ESCRIBIR UNA RESEÑA',
    'product.reviews.empty': 'Sin reseñas aún. ¡Sé el primero en opinar!',
    // REVIEW FORM
    'review.title': 'RESEÑA',
    'review.rating': 'PUNTUACIÓN',
    'review.title_label': 'TÍTULO',
    'review.title_placeholder': 'Ej: Excelente calidad',
    'review.comment_label': 'OPINIÓN',
    'review.comment_placeholder': 'Contá tu experiencia con el producto...',
    'review.condition': 'El producto llegó en buen estado y a tiempo',
    'review.submit': 'PUBLICAR RESEÑA',
    // CHECKOUT
    'checkout.title': 'FINALIZAR COMPRA',
    'checkout.step1': 'DATOS',
    'checkout.step2': 'ENVÍO',
    'checkout.step3': 'PAGO',
    'checkout.personal': 'DATOS PERSONALES',
    'checkout.name': 'NOMBRE *',
    'checkout.name_pl': 'Juan',
    'checkout.lastname': 'APELLIDO *',
    'checkout.lastname_pl': 'Pérez',
    'checkout.email': 'EMAIL *',
    'checkout.email_pl': 'juan@email.com',
    'checkout.phone': 'TELÉFONO',
    'checkout.phone_pl': '+54 9 11 0000-0000',
    'checkout.address_title': 'DIRECCIÓN DE ENVÍO',
    'checkout.address': 'DIRECCIÓN *',
    'checkout.address_pl': 'Av. Corrientes 1234',
    'checkout.city': 'CIUDAD *',
    'checkout.city_pl': 'Buenos Aires',
    'checkout.zip': 'CÓDIGO POSTAL *',
    'checkout.zip_pl': '1000',
    'checkout.province': 'PROVINCIA *',
    'checkout.continue': 'CONTINUAR',
    'checkout.shipping_title': 'MÉTODO DE ENVÍO',
    'checkout.shipping_cost_title': 'COSTO DE ENVÍO',
    'checkout.shipping_cost_text': 'El costo exacto queda **pendiente** y se calcula una vez confirmada la dirección de entrega. Lo verás reflejado en el total final antes de pagar.',
    'checkout.back': 'VOLVER',
    'checkout.payment_title': 'MÉTODO DE PAGO',
    'checkout.mp': 'MERCADO PAGO',
    'checkout.mp_desc': 'Tarjeta, efectivo, cuotas',
    'checkout.card': 'TARJETA DE CRÉDITO / DÉBITO',
    'checkout.card_desc': 'Hasta 12 cuotas sin interés',
    'checkout.transfer': 'TRANSFERENCIA BANCARIA',
    'checkout.transfer_desc': '10% de descuento adicional',
    'checkout.card_number': 'NÚMERO DE TARJETA',
    'checkout.card_pl': '0000 0000 0000 0000',
    'checkout.expiry': 'VENCIMIENTO',
    'checkout.expiry_pl': 'MM/AA',
    'checkout.cvv': 'CVV',
    'checkout.cvv_pl': '000',
    'checkout.card_name': 'NOMBRE EN LA TARJETA',
    'checkout.card_name_pl': 'JUAN PEREZ',
    'checkout.confirm': 'CONFIRMAR PEDIDO',
    'checkout.order_summary': 'TU PEDIDO',
    'checkout.subtotal': 'SUBTOTAL',
    'checkout.shipping': 'ENVÍO',
    'checkout.pending': 'PENDIENTE',
    'checkout.total': 'TOTAL',
    'checkout.coupon': 'CUPÓN DE DESCUENTO',
    'checkout.coupon_pl': 'INGRESÁ TU CÓDIGO',
    'checkout.apply': 'APLICAR',
    'checkout.shipping_note': 'EL COSTO DE ENVÍO SE CALCULA ANTES DE CONFIRMAR EL PAGO',
    // LOGIN
    'login.subtitle': 'ACCEDÉ A TU CUENTA',
    'login.verify_title': 'VERIFICÁ TU EMAIL',
    'login.verify_text': 'Tu cuenta no está verificada. Revisá tu bandeja de entrada y hacé clic en el link que te enviamos.',
    'login.resend': 'REENVIAR EMAIL DE VERIFICACIÓN',
    'login.email': 'EMAIL',
    'login.email_pl': 'tu@email.com',
    'login.password': 'CONTRASEÑA',
    'login.password_pl': '••••••••',
    'login.remember': 'RECORDAR MI CUENTA',
    'login.forgot': '¿OLVIDASTE TU CONTRASEÑA?',
    'login.submit': 'INICIAR SESIÓN',
    'login.or': 'O CONTINUÁ CON',
    'login.google': 'INICIAR CON GOOGLE',
    'login.noaccount': '¿No tenés cuenta?',
    'login.register': 'REGISTRATE',
    
    // REGISTER
    'register.subtitle': 'CREÁ TU CUENTA',
    'register.name': 'NOMBRE *',
    'register.name_pl': 'Juan',
    'register.lastname': 'APELLIDO *',
    'register.lastname_pl': 'Pérez',
    'register.email': 'EMAIL *',
    'register.email_pl': 'tu@email.com',
    'register.password': 'CONTRASEÑA *',
    'register.password_pl': 'Mínimo 8 caracteres',
    'register.confirm': 'CONFIRMAR CONTRASEÑA *',
    'register.confirm_pl': 'Repetí tu contraseña',
    'register.accept': 'Acepto los',
    'register.terms': 'Términos y Condiciones',
    'register.and': 'y la',
    'register.privacy': 'Política de Privacidad',
    'register.submit': 'CREAR CUENTA',
    'register.hasaccount': '¿Ya tenés cuenta?',
    'register.signin': 'INICIÁ SESIÓN',
    'register.success_title': '¡REVISÁ TU EMAIL!',
    'register.success_text1': 'Te enviamos un correo de verificación a:',
    'register.success_text2': 'Hacé clic en el link del email para activar tu cuenta y acceder a todas las funciones.',
    'register.success_cta': 'IR AL INICIO DE SESIÓN',
    'register.resend': 'REENVIAR EMAIL',
    'register.success_spam': '¿No lo encontrás? Revisá la carpeta de spam o correo no deseado.',
    // ACCOUNT
    'account.title': 'MI CUENTA',
    'account.orders': 'MIS PEDIDOS',
    'account.profile': 'MI PERFIL',
    'account.payment': 'MÉTODOS DE PAGO',
    'account.addresses': 'DIRECCIONES',
    'account.security': 'SEGURIDAD',
    'account.data': 'TUS DATOS',
    'account.logout': 'CERRAR SESIÓN',
    'account.orders_empty': 'NO TENÉS PEDIDOS AÚN',
    'account.start_shopping': 'EMPEZAR A COMPRAR',
    'account.profile_title': 'DATOS PERSONALES',
    'account.name': 'NOMBRE *',
    'account.name_pl': 'Tu nombre',
    'account.lastname': 'APELLIDO *',
    'account.lastname_pl': 'Tu apellido',
    'account.phone': 'TELÉFONO',
    'account.phone_pl': '+54 9 11 0000-0000',
    'account.dni': 'DNI',
    'account.dni_pl': '12.345.678',
    'account.birth': 'FECHA DE NACIMIENTO',
    'account.gender': 'GÉNERO',
    'account.gender_none': 'Prefiero no decir',
    'account.gender_male': 'Masculino',
    'account.gender_female': 'Femenino',
    'account.gender_nb': 'No binario',
    'account.gender_other': 'Otro',
    'account.save': 'GUARDAR CAMBIOS',
    // WHATSAPP
    'whatsapp.tooltip': 'Contactanos por WhatsApp',
    // SIZE GUIDE
    'sizeguide.title': 'GUÍA DE TALLES',
    'sizeguide.size': 'TALLE',
    'sizeguide.chest': 'PECHO (CM)',
    'sizeguide.waist': 'CINTURA (CM)',
    'sizeguide.hip': 'CADERA (CM)',
    'sizeguide.footer': 'Medidas en centímetros. En caso de duda, elegí el talle más grande.',
    // ORDER CONFIRMATION
    'orderconfirm.title': '¡PEDIDO CONFIRMADO!',
    'orderconfirm.subtitle': 'Gracias por tu compra. Te enviamos los detalles a tu email.',
  },
  en: {
    // SPLASH
    'splash.x': 'X',
    'splash.i': 'I',
    'splash.n': 'N',
    'splash.c': 'C',
    'splash.o': 'O',
    // META
    'meta.desc': 'XINCO. Impeccable cut and premium materials. Shipping nationwide.',
    'meta.ogdesc': 'Discover the XINCO collection. Unique style garments.',
    'meta.twdesc': 'Discover the XINCO collection.',
    // CART
    'cart.title': 'YOUR CART',
    'cart.subtotal': 'SUBTOTAL',
    'cart.shipping': 'SHIPPING',
    'cart.free': 'FREE',
    'cart.checkout': 'CHECKOUT',
    'cart.continue': 'CONTINUE SHOPPING',
    // MOBILE MENU
    'mobile.home': 'HOME',
    'mobile.catalog': 'CATALOG',
    'mobile.accessories': 'ACCESSORIES',
    'mobile.new': 'NEW',
    'mobile.exclusive': 'EXCLUSIVE',
    // SEARCH
    'search.title': 'SEARCH',
    'search.hint': 'CTRL+K TO OPEN / ESC TO CLOSE',
    'search.suggestions': 'SUGGESTIONS:',
    'search.shirts': 'T-SHIRTS',
    'search.hoodies': 'HOODIES',
    'search.pants': 'PANTS',
    'search.new': 'NEW ARRIVALS',
    'search.sale': 'SALE',
    'search.empty': 'NO RESULTS — TRY A DIFFERENT TERM',
    // HEADER
    'header.login': 'LOG IN',
    'header.customize': 'Customize',
    // NAV
    'nav.home': 'HOME',
    'nav.catalog': 'CATALOG',
    'nav.accessories': 'ACCESSORIES',
    'nav.new': 'NEW',
    'nav.exclusive': 'EXCLUSIVE',
    // THEME PANEL
    'theme.title': 'Theme',
    'theme.light': 'Light',
    'theme.dark': 'Dark',
    'theme.soft': 'Soft',
    'theme.accent': 'Accent',
    // HERO
    'hero.explore': 'EXPLORE COLLECTION',
    'hero.new': 'NEW ARRIVALS',
    // CATEGORIES
    'categories.title': 'Categories',
    'categories.shirts': 'T-Shirts',
    'categories.pants': 'Pants',
    'categories.hoodies': 'Hoodies',
    'categories.accessories': 'Accessories',
    // HOME SECTIONS
    'home.newarrivals.label': 'NEW ARRIVALS',
    'home.newarrivals.title': 'Just dropped',
    'home.newarrivals.seeall': 'SEE ALL',
    'home.exclusive.label': 'EXCLUSIVE',
    'home.exclusive.title': 'Limited edition',
    'home.exclusive.seeall': 'SEE ALL',
    // PROMO
    'promo.apply': 'Apply code at checkout.',
    'promo.claim': 'CLAIM NOW',
    // TRUST BAR
    'trust.shipping.title': 'SHIPPING NATIONWIDE',
    'trust.shipping.desc': 'Delivery in 3-7 business days',
    'trust.returns.title': 'FREE RETURNS',
    'trust.returns.desc': 'Within 30 days',
    'trust.payment.title': 'SECURE PAYMENT',
    'trust.payment.desc': 'Wire, debit or credit',
    'trust.support.title': 'DIRECT SUPPORT',
    'trust.support.desc': 'We reply instantly on WhatsApp',
    // ABOUT
    'about.label': 'THE BRAND',
    'about.text': 'We were born in Mar del Plata with a clear idea: to break the mold. XINCO is not just clothing, it is a way to express who you are. Garments with impeccable cut, premium materials, and a style that speaks for itself. Every collection is designed for those who walk their own path.',
    'about.cta': 'DISCOVER THE COLLECTION',
    // INSTAGRAM
    'instagram.label': '@XINCO.STORE',
    'instagram.title': 'Follow us on Instagram',
    // FOOTER
    'footer.rights': 'All Rights Reserved.',
    'footer.location': 'Mar del Plata, Buenos Aires, Argentina.',
    'footer.shop': 'SHOP',
    'footer.catalog': 'Catalog',
    'footer.new': 'New Arrivals',
    'footer.hoodies': 'Hoodies',
    'footer.shirts': 'T-Shirts',
    'footer.accessories': 'Accessories',
    'footer.exclusive': 'EXCLUSIVE',
    'footer.help': 'HELP',
    'footer.sizeguide': 'Size Guide',
    'footer.shipping': 'Shipping',
    'footer.returns': 'Returns',
    'footer.contact': 'Contact',
    'footer.newsletter': 'NEWSLETTER',
    'footer.newsletter.desc': 'Be the first to know about drops.',
    'footer.newsletter.email': 'your@email.com',
    'footer.newsletter.ok': 'OK',
    'footer.copyright': '© 2025 XINCO — MAR DEL PLATA, BUENOS AIRES, ARGENTINA',
    // CATALOG PAGE
    'catalog.title': 'ALL ITEMS',
    'catalog.subtitle': 'Explore our collection.',
    'catalog.filter.category': 'CATEGORY',
    'catalog.filter.all': 'All',
    'catalog.filter.tshirts': 'T-Shirts',
    'catalog.filter.pants': 'Pants',
    'catalog.filter.hoodies': 'Hoodies',
    'catalog.filter.jackets': 'Jackets',
    'catalog.filter.accessories': 'Accessories',
    'catalog.filter.size': 'SIZE',
    'catalog.filter.color': 'COLOR',
    'catalog.filter.price': 'PRICE',
    'catalog.filter.clear': 'CLEAR FILTERS',
    'catalog.sort': 'SORT BY:',
    'catalog.sort.relevance': 'RELEVANCE',
    'catalog.sort.price_asc': 'PRICE: LOW TO HIGH',
    'catalog.sort.price_desc': 'PRICE: HIGH TO LOW',
    'catalog.sort.newest': 'NEWEST',
    'catalog.empty': 'NO PRODUCTS FOUND',
    'catalog.empty.cta': 'SEE ALL',
    // ACCESSORIES PAGE
    'accessories.title': 'ACCESSORIES',
    'accessories.subtitle': 'Caps, bracelets, earrings, chains and more.',
    'accessories.sort': 'SORT BY:',
    'accessories.sort.relevance': 'RELEVANCE',
    'accessories.sort.price_asc': 'PRICE: LOW TO HIGH',
    'accessories.sort.price_desc': 'PRICE: HIGH TO LOW',
    'accessories.sort.newest': 'NEWEST',
    'accessories.empty': 'NO ACCESSORIES AVAILABLE',
    // PRODUCT OVERLAY
    'product.breadcrumb.home': 'HOME',
    'product.breadcrumb.catalog': 'CATALOG',
    'product.breadcrumb.product': 'PRODUCT',
    'product.zoom': 'ZOOM',
    'product.color': 'COLOR:',
    'product.size': 'SIZE:',
    'product.sizeguide': 'SIZE GUIDE',
    'product.addtocart': 'ADD TO CART',
    'product.favorite': 'SAVE TO FAVORITES',
    'product.sku': 'SKU',
    'product.category': 'CATEGORY',
    'product.stock': 'STOCK',
    'product.shipping_info': 'FREE SHIPPING OVER $95,000',
    'product.returns_info': '30-DAY RETURN GUARANTEE',
    'product.related': 'YOU MAY ALSO LIKE',
    'product.reviews': 'REVIEWS',
    'product.reviews.count': '0 REVIEWS',
    'product.reviews.write': 'WRITE A REVIEW',
    'product.reviews.empty': 'No reviews yet. Be the first!',
    // REVIEW FORM
    'review.title': 'REVIEW',
    'review.rating': 'RATING',
    'review.title_label': 'TITLE',
    'review.title_placeholder': 'E.g.: Great quality',
    'review.comment_label': 'REVIEW',
    'review.comment_placeholder': 'Tell us about your experience...',
    'review.condition': 'The product arrived on time and in good condition',
    'review.submit': 'PUBLISH REVIEW',
    // CHECKOUT
    'checkout.title': 'CHECKOUT',
    'checkout.step1': 'DETAILS',
    'checkout.step2': 'SHIPPING',
    'checkout.step3': 'PAYMENT',
    'checkout.personal': 'PERSONAL DETAILS',
    'checkout.name': 'FIRST NAME *',
    'checkout.name_pl': 'John',
    'checkout.lastname': 'LAST NAME *',
    'checkout.lastname_pl': 'Doe',
    'checkout.email': 'EMAIL *',
    'checkout.email_pl': 'john@email.com',
    'checkout.phone': 'PHONE',
    'checkout.phone_pl': '+1 555 000 0000',
    'checkout.address_title': 'SHIPPING ADDRESS',
    'checkout.address': 'ADDRESS *',
    'checkout.address_pl': '123 Main St',
    'checkout.city': 'CITY *',
    'checkout.city_pl': 'New York',
    'checkout.zip': 'ZIP CODE *',
    'checkout.zip_pl': '10001',
    'checkout.province': 'STATE *',
    'checkout.continue': 'CONTINUE',
    'checkout.shipping_title': 'SHIPPING METHOD',
    'checkout.shipping_cost_title': 'SHIPPING COST',
    'checkout.shipping_cost_text': 'The exact cost is **pending** and will be calculated once the delivery address is confirmed. You will see it in the final total before payment.',
    'checkout.back': 'BACK',
    'checkout.payment_title': 'PAYMENT METHOD',
    'checkout.mp': 'MERCADO PAGO',
    'checkout.mp_desc': 'Card, cash, installments',
    'checkout.card': 'CREDIT / DEBIT CARD',
    'checkout.card_desc': 'Up to 12 interest-free installments',
    'checkout.transfer': 'BANK TRANSFER',
    'checkout.transfer_desc': '10% additional discount',
    'checkout.card_number': 'CARD NUMBER',
    'checkout.card_pl': '0000 0000 0000 0000',
    'checkout.expiry': 'EXPIRY',
    'checkout.expiry_pl': 'MM/YY',
    'checkout.cvv': 'CVV',
    'checkout.cvv_pl': '000',
    'checkout.card_name': 'NAME ON CARD',
    'checkout.card_name_pl': 'JOHN DOE',
    'checkout.confirm': 'CONFIRM ORDER',
    'checkout.order_summary': 'YOUR ORDER',
    'checkout.subtotal': 'SUBTOTAL',
    'checkout.shipping': 'SHIPPING',
    'checkout.pending': 'PENDING',
    'checkout.total': 'TOTAL',
    'checkout.coupon': 'DISCOUNT COUPON',
    'checkout.coupon_pl': 'ENTER YOUR CODE',
    'checkout.apply': 'APPLY',
    'checkout.shipping_note': 'SHIPPING COST IS CALCULATED BEFORE CONFIRMING PAYMENT',
    // LOGIN
    'login.subtitle': 'ACCESS YOUR ACCOUNT',
    'login.verify_title': 'VERIFY YOUR EMAIL',
    'login.verify_text': 'Your account is not verified. Check your inbox and click the link we sent.',
    'login.resend': 'RESEND VERIFICATION EMAIL',
    'login.email': 'EMAIL',
    'login.email_pl': 'your@email.com',
    'login.password': 'PASSWORD',
    'login.password_pl': '••••••••',
    'login.remember': 'REMEMBER ME',
    'login.forgot': 'FORGOT YOUR PASSWORD?',
    'login.submit': 'SIGN IN',
    'login.or': 'OR CONTINUE WITH',
    'login.google': 'SIGN IN WITH GOOGLE',
    'login.noaccount': "Don't have an account?",
    'login.register': 'SIGN UP',
    
    // REGISTER
    'register.subtitle': 'CREATE YOUR ACCOUNT',
    'register.name': 'FIRST NAME *',
    'register.name_pl': 'John',
    'register.lastname': 'LAST NAME *',
    'register.lastname_pl': 'Doe',
    'register.email': 'EMAIL *',
    'register.email_pl': 'your@email.com',
    'register.password': 'PASSWORD *',
    'register.password_pl': 'Minimum 8 characters',
    'register.confirm': 'CONFIRM PASSWORD *',
    'register.confirm_pl': 'Repeat your password',
    'register.accept': 'I accept the',
    'register.terms': 'Terms and Conditions',
    'register.and': 'and the',
    'register.privacy': 'Privacy Policy',
    'register.submit': 'CREATE ACCOUNT',
    'register.hasaccount': 'Already have an account?',
    'register.signin': 'SIGN IN',
    'register.success_title': 'CHECK YOUR EMAIL!',
    'register.success_text1': 'We sent a verification email to:',
    'register.success_text2': 'Click the link in the email to activate your account and access all features.',
    'register.success_cta': 'GO TO LOGIN',
    'register.resend': 'RESEND EMAIL',
    'register.success_spam': "Can't find it? Check your spam or junk mail folder.",
    // ACCOUNT
    'account.title': 'MY ACCOUNT',
    'account.orders': 'MY ORDERS',
    'account.profile': 'MY PROFILE',
    'account.payment': 'PAYMENT METHODS',
    'account.addresses': 'ADDRESSES',
    'account.security': 'SECURITY',
    'account.data': 'YOUR DATA',
    'account.logout': 'SIGN OUT',
    'account.orders_empty': 'NO ORDERS YET',
    'account.start_shopping': 'START SHOPPING',
    'account.profile_title': 'PERSONAL DETAILS',
    'account.name': 'FIRST NAME *',
    'account.name_pl': 'Your name',
    'account.lastname': 'LAST NAME *',
    'account.lastname_pl': 'Your last name',
    'account.phone': 'PHONE',
    'account.phone_pl': '+1 555 000 0000',
    'account.dni': 'ID NUMBER',
    'account.dni_pl': '12.345.678',
    'account.birth': 'DATE OF BIRTH',
    'account.gender': 'GENDER',
    'account.gender_none': 'Prefer not to say',
    'account.gender_male': 'Male',
    'account.gender_female': 'Female',
    'account.gender_nb': 'Non-binary',
    'account.gender_other': 'Other',
    'account.save': 'SAVE CHANGES',
    // WHATSAPP
    'whatsapp.tooltip': 'Contact us on WhatsApp',
    // SIZE GUIDE
    'sizeguide.title': 'SIZE GUIDE',
    'sizeguide.size': 'SIZE',
    'sizeguide.chest': 'CHEST (CM)',
    'sizeguide.waist': 'WAIST (CM)',
    'sizeguide.hip': 'HIP (CM)',
    'sizeguide.footer': 'Measurements in centimeters. When in doubt, choose the larger size.',
    // ORDER CONFIRMATION
    'orderconfirm.title': 'ORDER CONFIRMED!',
    'orderconfirm.subtitle': 'Thank you for your purchase. We sent the details to your email.',
  },
};

let currentLang = 'es';

function t(key) {
  return translations[currentLang]?.[key] ?? translations.es[key] ?? key;
}

function getLang() {
  return currentLang;
}

function setLang(lang) {
  if (!translations[lang]) return;
  currentLang = lang;
  localStorage.setItem(LANG_KEY, lang);
  document.documentElement.lang = lang;
  const label = document.getElementById('lang-label');
  if (label) label.textContent = lang === 'en' ? 'EN' : 'ES';
  const btn = document.getElementById('lang-toggle');
  if (btn) btn.title = lang === 'en' ? 'Switch language' : 'Cambiar idioma';
  applyTranslations();
  import('./auth.js').then(m => m.updateAuthUI());
}

function toggleLang() {
  const current = getLang();
  const next = current === 'es' ? 'en' : 'es';
  setLang(next);
}

function applyTranslations() {
  document.querySelectorAll('[data-i18n]').forEach(el => {
    el.textContent = t(el.getAttribute('data-i18n'));
  });
  document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
    el.placeholder = t(el.getAttribute('data-i18n-placeholder'));
  });
  document.querySelectorAll('[data-i18n-title]').forEach(el => {
    el.title = t(el.getAttribute('data-i18n-title'));
  });
  document.querySelectorAll('[data-i18n-value]').forEach(el => {
    el.value = t(el.getAttribute('data-i18n-value'));
  });
  document.querySelectorAll('[data-i18n-html]').forEach(el => {
    el.innerHTML = t(el.getAttribute('data-i18n-html'));
  });
}

function init(savedLang) {
  if (savedLang && translations[savedLang]) {
    currentLang = savedLang;
  } else {
    const stored = localStorage.getItem(LANG_KEY);
    if (stored && translations[stored]) {
      currentLang = stored;
    }
  }
  document.documentElement.lang = currentLang;
  window.t = t;
  window.__ = t;
  window.setLang = setLang;
  window.toggleLang = toggleLang;
  applyTranslations();
}

export { t, getLang, setLang, applyTranslations, init, LANG_KEY, translations };
